### ISSUE TITLE
Whitelisted IP's getting banned

### ISSUE THREAD

**Issue by Tormiasz** [jgmdev/ddos-deflate#1]
Hello.
I've whitelisisted my IP, restarted the daemon and I am still getting banned after reaching the connection limit. "ddos --i" shows my IP as whitelisted so it should work. System is Debian 6, running as daemon.

Greetings.

**Comment by Tormiasz** [comment]
The problem was (propably) with dnsutils not being installed.

**Comment by jgmdev** [comment]
Good to know, maybe we can add a note of requirements into the readme or modify the script in case some required command isn't found.

**Comment by Tormiasz** [comment]
Indeed, good idea. nslookup was the command I didn't have on my server.
