### ISSUE TITLE
error: Required dependency 'tcpkill' is missing.

### ISSUE THREAD

**Issue by msergiy87** [jgmdev/ddos-deflate#10]
Hello
Unfortunately there is no tcpkill package in Debian Wheezy repository and I can't install and use it.
Thanks

**Comment by gagomap** [comment]
Install dsniff package will fix it

`sudo apt-get install dsniff`

**Comment by msergiy87** [comment]
Thank you

**Comment by mean-cj** [comment]
## Install dsniff on Centos 5 (64bit)
- rpm -Uvh http://dl.fedoraproject.org/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm
- yum install dsniff 

### Fixed
Required dependency 'timeout' is missing.
- rpm -ivh ftp://ftp.pbone.net/mirror/ftp5.gwdg.de/pub/opensuse/repositories/home:/crt0solutions:/extras/CentOS_CentOS-5/x86_64/timeout-8.4-20.3.crt0.x86_64.rpm

## Install dsniff on Centos 6 (64bit)
- rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
- yum install dsniff

**Comment by msergiy87** [comment]
Thank you too

**Comment by mean-cj** [comment]
## Installing dsniff from soruce

Prerequisites packages for centos/RHEL
libpcap , libpcap-devel , libnet , libnet-devel , libnids

# yum install libpcap libpcap-devel libnet libnet-devel libnids
Download dsniff tar from http://monkey.org/~dugsong/dsniff/

cd /usr/src
wget http://monkey.org/~dugsong/dsniff/dsniff-2.3.tar.gz
tar zxvf dsniff-2.3.tar.gz
cd dsniff-2.3
./configure && make && make install

credit: http://www.gnutoolbox.com/dsniff/

**Comment by jgmdev** [comment]
Would be nice to add a wiki page with all dependencies needed for the different flavors of linux :)

**Comment by ponyvps** [comment]
> Fixed
> Required dependency 'timeout' is missing.
>     rpm -ivh ftp://ftp.pbone.net/mirror/ftp5.gwdg.de/pub/opensuse/repositories/home:/crt0solutions:/extras/CentOS_CentOS-5/x86_64/timeout-8.4-20.3.crt0.x86_64.rpm
> 

and this

> Installing dsniff from soruce
> 
> Prerequisites packages for centos/RHEL
> libpcap , libpcap-devel , libnet , libnet-devel , libnids
> 
> yum install libpcap libpcap-devel libnet libnet-devel libnids
> Download dsniff tar from http://monkey.org/~dugsong/dsniff/
> 
> cd /usr/src
> wget http://monkey.org/~dugsong/dsniff/dsniff-2.3.tar.gz
> tar zxvf dsniff-2.3.tar.gz
> cd dsniff-2.3
> ./configure && make && make install


both above not worked.

tested on openvz (centos 5.10 32bit)

**Comment by ponyvps** [comment]
ddos-deflate-master]# ddos -d
shell-init: error retrieving current directory: getcwd: cannot access parent dir                                                                                                                     ectories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent dir                                                                                                                     ectories: No such file or directory
