### ISSUE TITLE
can i whitlist ips with asterisks to mark a ip range

### ISSUE THREAD

**Issue by stevang** [jgmdev/ddos-deflate#18]
since there are tons of cloudflare ips to whitelist, is it working when i do it like that?

`111.222.*.*`
`33.44.55.*`
etc

**Comment by msergiy87** [comment]
see my repository. But you should a little change my script for you needs.
https://github.com/msergiy87/ddos-deflate-custom

**Comment by jgmdev** [comment]
#45 implements a solution.
