### ISSUE TITLE
Why not support blacklist?

### ISSUE THREAD

**Issue by Mr-xn** [jgmdev/ddos-deflate#35]
Why not support blacklist?

**Comment by jgmdev** [comment]
that would be a nice feature accompanied with a known list of bad ip's. Pull requests welcome.

**Comment by amgadfahmi** [comment]
any update on this !

**Comment by jgmdev** [comment]
For those interested on blacklisting I wrote this script https://github.com/jgmdev/stopspam some time ago which is really similar to this one but only for blacklisting known bad ip's, it keeps the blacklists automatically updated. I just updated it with ipv6 support (taking some of the changes and ideas on ddos-deflate) and beside improving stopforumspam support I also added spamhaus drop lists which seems to be a nice collection.

**Comment by Cyberbolt** [comment]
You can try [cfw](https://github.com/Cyberbolt/cfw).
