### ISSUE TITLE
/etc/cron.d/ddos is created with strange code

### ISSUE THREAD

**Issue by r00t8** [jgmdev/ddos-deflate#36]
> # cat /etc/cron.d/ddos
0-59/1 ChangeLog config install.sh LICENSE Makefile man README.md src uninstall.sh ChangeLog config install.sh LICENSE Makefile man README.md src uninstall.sh ChangeLog config install.sh LICENSE Makefile man README.md src uninstall.sh ChangeLog config install.sh LICENSE Makefile man README.md src uninstall.sh root /usr/local/sbin/ddos -k >/dev/null 2>&1

**Comment by Mr-xn** [comment]
@r00t8  these likes your  root directory file?

**Comment by HorselessName** [comment]
Same here. Using Debian 7

**Comment by jgmdev** [comment]
Fixed on latest commit and this issue was caused because a variable that contains * characters needs to be double quoted in order for the shell to not evaluate the *. In any case this feature now throws a deprecation warning since daemon mode is faster and better.
