### ISSUE TITLE
Not compatible with Debian or another Distributionen

### ISSUE THREAD

**Issue by Lacrimosa99** [jgmdev/ddos-deflate#4]
Your Program is not compatible with another Distributionen like Ubuntu or Debian.

Can you rewrite the Code for Ubuntu/Debian?

**Comment by jgmdev** [comment]
It does works under debian, since I have deployed it to debian installations, maybe you are missing some dependencies, it was reported on issue #1 that the dnsutils package solved the issues under debian.

In any case you can try troubleshooting by running the script with:

ddos -v or ddos --loop

**Comment by jgmdev** [comment]
Added dependencies check on installer script.
