### ISSUE TITLE
Unable to install via SSH on Shared CentOS Hosting 

### ISSUE THREAD

**Issue by codeslane** [jgmdev/ddos-deflate#41]
<img width="1440" alt="screen shot 2018-02-23 at 5 24 05 pm" src="https://user-images.githubusercontent.com/26877201/36593087-615c1a62-18be-11e8-97da-171797293cb0.png">

**Comment by Mr-xn** [comment]
@codeslane  your notion was said  " error: Required dependency 'nslookup' is missing " , maybe you can try this command : yum update && yum install nslookup

**Comment by codeslane** [comment]
I'm still not able to update the nslookup .. or sudo

**Comment by dfmcvn** [comment]
shared hosting does not allow you to use `sudo` command or install anything, you should try on a vps or dedicated server

**Comment by jgmdev** [comment]
Closing as this is a server access rights issue.
