### ISSUE TITLE
ddos service doesn't autostart at boot

### ISSUE THREAD

**Issue by gagomap** [jgmdev/ddos-deflate#5]
Hi,
I 'm using EasyEngine on Ubuntu 14.04 LTS. I have found ddos service doesn't start at boot. I always start it manually.

**Comment by maneesh1** [comment]
Have come across the same issue  on Ubuntu 14.04.

pretty sure that the install script here should take care of it... and we do see the "ddos.conf" file under /etc/init.d

update-rc.d ddos defaults > /dev/null 2>&1


but, still doesn't autostart on boot

**Comment by jgmdev** [comment]
Fixed on latest commits by improving the initd script.
