### ISSUE TITLE
centos7.4 yum no package grepcidr available.

### ISSUE THREAD

**Issue by katanala** [jgmdev/ddos-deflate#53]
@jgmdev hello，i use centos7.4 system and installed this script. but it not work. i found my system have no “grepcidr”, so i want to install “grepcidr”  by command "yum install  grepcidr"，it shows error："No package grepcidr available." 
so, i want to konw how to solve it. where i can download your grepcide and install it. thanks.

**Comment by jgmdev** [comment]
Something like this should do it:
```sh
wget http://www.pc-tools.net/files/unix/grepcidr-2.0.tar.gz
tar -xvzf grepcidr-2.0.tar.gz
cd  grepcidr-2.0
make
make PREFIX=/usr install
```
