### ISSUE TITLE
I cant' view the IP with ddos -v[4|6]

### ISSUE THREAD

**Issue by carlosanpardo** [jgmdev/ddos-deflate#54]
Hello! I recently install in a new machine the script "ddos" but using the command ddos -v appear again the help commands list.

https://snag.gy/Yw0j8t.jpg

I try with the below options without success:

ddos -v -4
ddos -v4
ddos -v 4
ddos -v[4|6]
ddos -v[4]

My OS is: CentOS release 6.9.

Thank you

**Comment by jgmdev** [comment]
It seems the ss  version shipped with that centos version is too old. In order to fix this I would need to add some option to force netstat usage if the ss version is old.... 

You can also try a more recent version of centos.

**Comment by katanala** [comment]
@carlosanpardo  maybe, you can try :

yum -y update

**Comment by katanala** [comment]
@carlosanpardo  I've also had this problem. the version of my centos7.4's ss is old too. i use command "yum -y update" solved this problem.

**Comment by dikkatdeli** [comment]
My version is CentOS Linux release 7.6.1810 (Core)

There is no output with these commands : 

ddos -v -4
ddos -v4
ddos -v 4
ddos -v[4|6]
ddos -v[4]

**Comment by dikkatdeli** [comment]
sorry for late reply. 

I did:  yum -y update
and it said : Complete!

still no output guys.

i get output with this : ss -Hntu | awk '{print $6}' | sort | uniq -c | sort -nr

but not any command with ddos.
