### ISSUE TITLE
System support list after upgrading this version

### ISSUE THREAD

**Issue by zhq1** [jgmdev/ddos-deflate#55]
Can this updated version be based on centos 7.x or higher only? My system is centos 6.3 x64 bit, run ss -Hntu | awk '{print $6}' | sort | uniq -c | sort -nr command prompt ss: invalid option -- 'H'

**Comment by jgmdev** [comment]
You can change this line https://github.com/jgmdev/ddos-deflate/blob/master/src/ddos.sh#L48 to false so it always use netstat instead of ss

**Comment by jgmdev** [comment]
Correction! this line to true https://github.com/jgmdev/ddos-deflate/blob/master/src/ddos.sh#L45

**Comment by zhq1** [comment]
thanks

**Comment by jgmdev** [comment]
Referencing #54 and closing.
