### ISSUE TITLE
Cloudflare support

### ISSUE THREAD

**Issue by budflick** [jgmdev/ddos-deflate#59]
hi jgmdev,

I installed this on centos 7 and when i tried to simulate ddos in my server/site, the **ddos -v** lists the various Cloudflare IPs as the attacker, and the connection count range from ~1 - ~100, effectively not blocking anything below the treshold.

Can you help how can this be fixed? The bulk of attack is from Cloudflare IP itself

**Comment by jgmdev** [comment]
What connection range isn't getting blocked? maybe your [ignore.ip.list](https://github.com/jgmdev/ddos-deflate/blob/master/config/ignore.ip.list) is permitting the undesired connections. Also you should set the [NO_OF_CONNECTIONS](https://github.com/jgmdev/ddos-deflate/blob/master/config/ddos.conf#L28) flag to the max desired amount of connections per ip.

**Comment by budflick** [comment]
Hi, 

Im using centos 7, in daemon mode. I havent included anything in ignore.ip.list except my shared host ip for remote database: 192.3.x.x. Also, the ddos.conf is modified only for NO_OF_CONNECTIONS=100 and FIREWALL=iptables as i am using vestacp.

Overall it worked. To clarify, when i simulate DOS on my ip/domain, the attacker IP is only 1 hit, and excessive hits are delivered by cloudflare IPs. 

My domain is under cloudflare-free, and my vps is using vestaCP. 

I see in issue #27 that the author was able to modify for cloudflare/nginx use, but that was outdated.

Please see the screenshot: http://prntscr.com/n3swe9  (the ip in red is my isp, which shows 1 hit. the ips in orange are cloudflare servers with massive hits in just few seconds of running HULK dos)

**Comment by jgmdev** [comment]
Ok lets see if I understand correctly...

You are using cloudflare to get some protection but instead cloudflare is distributing the dos attack on multiple servers and delivering it to your server? Isn't cloudflare supposed to prevent a dos attack since your server is behind their network? 

How do you know those orange connections are generated from your dos test? If that's the case then cloudflare is making matters worse (maybe on purpose)... 

Now I wonder if it's possible to monitor each connection cloud flare ip header (CF-Connecting-IP) using some tool since it is impossible to get that from ss or netstat alone (unless we scan a web server logs which seems unelegant)... that way we could know the real ip and add an iptable rule to drop those packets as I wrote on #27.

But using a rule like 
iptables -A INPUT -m string --algo bm --string "CF-Connecting-IP: A.B.C.D" -j DROP
would help but packets would still need to be analyzed which isn't great from a performance perspective. I have toyed with the idea of porting ddos to C to gain lower level access but I would need to learn many networking stuff as kernel things and I don't have enough free time for that so maybe there is a way to analyze each connection packet to see if the cloudflare ip is included and drop if too many of them.

**Comment by budflick** [comment]
Hi there, 

> You are using cloudflare to get some protection but instead cloudflare is distributing the dos attack on multiple servers and delivering it to your server? Isn't cloudflare supposed to prevent a dos attack since your server is behind their network?

My domain is behind cloudflare, and the vps is using VestaCP nginx+apache. This is the default config with cloudflare configs so the visitor IPs will be exposed  instead of CF-proxy ip: http://prntscr.com/n4bjyh

> How do you know those orange connections are generated from your dos test? If that's the case then cloudflare is making matters worse (maybe on purpose)...

See https://www.cloudflare.com/ips ... the vps/domain has few to no outside visit. When i use HULK.py dos tool, my own ip is there, just marked as 1 hit, while the CF ips populated the ddos.sh logs. as soon as i close the hulk dos, that IPs vanish.

> Now I wonder if it's possible to monitor each connection cloud flare ip header (CF-Connecting-IP) using some tool since it is impossible to get that from ss or netstat alone (unless we scan a web server logs which seems unelegant)... that way we could know the real ip and add an iptable rule to drop those packets as I wrote on #27.

I just passed on #27 but not sure how to correctly implement that. and the authors fork was outdated and not the same as yours so i dont want to mess with that.

> Using a rule like
iptables -A INPUT -m string --algo bm --string "CF-Connecting-IP: A.B.C.D" -j DROP
would help but packets would still need to be analyzed which isn't great from a performance perspective. I have toyed with the idea of porting ddos to C to gain lower level access but I would need to learn many networking stuff as kernel things and I don't have enough free time for that so maybe there is a way to analyze each connection packet to see if the cloudflare ip is included and drop if too many of them.

this is way beyond me now :( ... and as i assume, my prospect users will be chatters.. in that case they could have same IPs.. dropping could have a bad impact ?

**Comment by jgmdev** [comment]
Could you try running this command on the vps:
```
tcpdump -w output.pcap -n -A 'tcp port 80 or tcp port 443' | grep --line-buffered "CF-Connecting-IP:"
```
to monitor the received packets which include the CF ip header and launch the hulk dos test tool again and report the output?

Or much better run
```
tcpdump -w output.pcap
```
launch the dos test with hulk and when finished kill tcpdump with CTRL-C and upload the output.pcap file so I can analyze it with tcpdump locally.

**Comment by budflick** [comment]
Pre-dos https://budflick.com/output1.pcap
Ongoing-dos: https://budflick.com/output2.pcap
Post-dos: https://budflick.com/output3.pcap

**Comment by jgmdev** [comment]
Thanks! this worked beautifully:
```
tcpdump -r output2.pcap -n -A | grep CF-Connecting-IP:
```
With that we could maybe limit tcpdump for 1 second, grep the CF header and extract the ip's :)

**Comment by budflick** [comment]
> tcpdump -r output2.pcap -n -A | grep CF-Connecting-IP:

oh. so the logged CF-ips are false positive?

> With that we could maybe limit tcpdump for 1 second, grep the CF header and extract the ip's :)

pardon me, i dont know :(

if in theory i have 100 users with the same IP accessing the site at the same moment, some of them would be dropped? (i set the connection limit to 100)

**Comment by jgmdev** [comment]
As it seems cloudflare is distributing each of your request to a different cloudflare server and sending it to your VPS as you wrote before with the orange square of ip's screenshot. So basically we need a new ddos.conf option named CF_MODE=true|false (accompanied with implementation for it) that when true would also use tcpdump to retrieve the list of ip addresses (by reading the CF-Connecting-IP) that are making multiple connections behind the CF servers and block them using iptables string matching module. I will try to implement it but I will need for you to test it to see if it is working.

**Comment by budflick** [comment]
if you need to review my vps, i can give you the login.

> 
> 
> As it seems cloudflare is distributing each of your request to a different cloudflare server and sending it to your VPS as you wrote before with the orange square of ip's screenshot. So basically we need a new ddos.conf option named CF_MODE=true|false (accompanied with implementation for it) that when true would also use tcpdump to retrieve the list of ip addresses (by reading the CF-Connecting-IP) that are making multiple connections behind the CF servers and block them using iptables string matching module. I will try to implement it but I will need for you to test it to see if it is working.

I will be on the look-out, if you need my vps i can lend you the login. I think its better that you can also see if i have misconfigs.

**Comment by jgmdev** [comment]
Ok, I added the experimental cloudflare support! You will need to update ddos,sh with the most recent one on this repo and add ENABLE_CLOUDFLARE=true on your ddos.conf file, then you can restart ddos service and retest with hulkdos. By the way the -v flag now also includes cloudflare ip addresses found on the tcpdump file when ENABLE_CLOUDFLARE=trye so you can test that before running the hulkdos test. The tcpdump file is rotated every DAEMON_FREQ*2 seconds, not sure how well that will work so test and let me know.

**Comment by budflick** [comment]
> Ok, I added the experimental cloudflare support! You will need to update ddos,sh with the most recent one on this repo and add ENABLE_CLOUDFLARE=true on your ddos.conf file, then you can restart ddos service and retest with hulkdos. By the way the -v flag now also includes cloudflare ip addresses found on the tcpdump file when ENABLE_CLOUDFLARE=true so you can test that before running the hulkdos test. The tcpdump file is rotated every DAEMON_FREQ*2 seconds, not sure how well that will work so test and let me know.

It worked! 👍 but with a note:

1.) Normal visit to domain/host with updated ddos-deflate: 
**ddos -v** http://prntscr.com/n4kxzz 

- ddos-v shows my ISP ip and cloudflare ips. 
- Cloudflare ips should be listed on the "list of cloudflare ips". 
- CF-Connecting-IP already contains real visitor IP because its how configured in nginx https://prnt.sc/n4bjyh (recommended, default), but is incorrectly identified as cloudflare ip.

2.) During simulated hulk dos attack: 
**ddos -v** http://prntscr.com/n4l8gn 
**ddos -b** http://prntscr.com/n4l8xc
**tail /var/log/ddos.log** http://prntscr.com/n4l98t

- ddos-v incorrectly list the cloudflare ip as regular ips, and with empty "list of cloudflare ips" down (ISP ip was not shown because already banned by this time)
- ddos-b the banned ip is my ISP but listed in cloudflare list
- /var/log/ddos.log now shows the correct info, and my server ip was not included on the ban.

I confirm sir that this work regardless of the listed hits on ddos -v , is there still a need for the "list of cloudflare ip? but ddos -b should be reworked to just list the banned ip in one place?

Thank you very much 💯

**Comment by jgmdev** [comment]
> It worked! +1 but with a note (merely cosmetic) the "normal" and "cloudflare" ip listing is displayed incorrectly.

The normal listing displays ip addresses of connections directly made to the server, so if you are connecting to the vps using SSH your ip will also be listed on that list, that is why the cloudflare servers are listed because they are making direct connections to your server. On the other side the cloudflare ip list displays real user ip's of people indirectly connecting to the server using cloudflare reverse proxy servers, so the information displayed should be correct. (By the way I commit a change to hide the **reading from file...** message thrown by tcpdump when using the -v flag).

> Could a logic be developed to exclude the cloudflare ips from the ddos -v display list?

You can try adding the cloudflare ip's (103.21.244.0/22, 103.22.200.0/22, 103.31.4.0/22, etc...) on your **/etc/ddos/ignore.ip.list** file, and just in case you should add your vps ip to that list also (just in case so the server doesn't bans itself, since I'm not sure if it is retrieving its own ip properly).

Also out of curiosity how much time the server took to ban you when you launched the hulkdos test? Maybe I can remove the **experimental** message from the readme file :)

**Comment by budflick** [comment]
> The normal listing displays ip addresses of connections directly made to the server, so if you are connecting to the vps using SSH your ip will also be listed on that list, that is why the cloudflare servers are listed because they are making direct connections to your server. On the other side the cloudflare ip list displays real user ip's of people indirectly connecting to the server using cloudflare reverse proxy servers, so the information displayed should be correct.

Okay now i understand.. is it ok to rename as "List of CF-Connecting-IP" ?

>  (By the way I commit a change to hide the reading from file... message thrown by tcpdump when using the -v flag).

👍 

> You can try adding the cloudflare ip's (103.21.244.0/22, 103.22.200.0/22, 103.31.4.0/22, etc...) on your /etc/ddos/ignore.ip.list file, and just in case you should add your vps ip to that list also (just in case so the server doesn't bans itself, since I'm not sure if it is retrieving its own ip properly).

Wow. I forgot about this feature.  

> Also out of curiosity how much time the server took to ban you when you launched the hulkdos test? Maybe I can remove the experimental message from the readme file :)

Took around 2~3seconds after the surge of Cloudflare IPs 
[2019-03-30 00:26:30] banned 37.106.149.169 with 297 connections for ban period 600
[2019-03-30 00:37:49] banned 37.106.149.169 with 220 connections for ban period 600

Thanks!

**Comment by jgmdev** [comment]
> The default is DAEMON_FREQ=5, can it be lowered, or it will have performance impact?

that is multiplied by 2 to get 10 seconds total in order to give tcpdump enough time to collect data that can be analyzed, too little time I think would prevent enough data recollection to detect an attack. But yes, you can lower the daemon to 3 seconds interval so tcpdump will rotate every 6 seconds, you can try that and report back.

> note: i think i didn't see this before...
> Deleting cron job...sed: can't read /ddos/d: No such file or directory
> .. (done)

That was the installer? I need more details, in any case I will not be working until Sunday or Saturday late night have a nice day!

**Comment by budflick** [comment]
> that is multiplied by 2 to get 10 seconds total in order to give tcpdump enough time to collect data 

ah, i thought i need a lower number! i entered 1 and my ip didnt get banned when i changed it :D

> That was the installer? I need more details, in any case I will not be working until Sunday or Saturday late night have a nice day!

uninstall.sh .. im using centos7 and didnt remember seeing that on my first uninstall. needs message suppression maybe coz im using daemon mode.

other than that, this issue is solved, thank you very much

**Comment by jgmdev** [comment]
Since this seems to be working I will close the issue, by they way make sure to delete the pcap files you shared earlier to keep your server IP private.
