### ISSUE TITLE
IPs within ignored ranges still banned

### ISSUE THREAD

**Issue by stardust342** [jgmdev/ddos-deflate#6]
Hi,
I have added all the CloudFlare IPs to my ignore list, but IPs within that range are still getting banned.
Example: 108.162.192.0/18 ignored, yet 108.162.229.32 still banned.
I'm not sure if IP Range compatibility was intended, but I think it would be very useful.
Thanks.

**Comment by jgmdev** [comment]
Currently ranges are not supported but it seems that this resource will help to implement it:
http://technicalworldforyou.blogspot.com/2013/06/ipcalc-command-line-tool-for.html
http://stackoverflow.com/questions/10768160/ip-address-converter

**Comment by ttcttctw** [comment]
Any update for this? Just want to know when it's going to supportIP range

**Comment by bigqiang** [comment]
After adding ip into this file(ignore.ip.list), set it read-only. 
```bash
chmod 400 ignore.ip.list
```

**Comment by safly** [comment]
It will support :)

**Comment by jgmdev** [comment]
Implemented by @safly (thank you!)  on #45, #46, #47 and #48 so closing.
