### ISSUE TITLE
Can the ddos-deflate script prevent banning good Cloudflare IPs (are there such IPs)?

### ISSUE THREAD

**Issue by slrslr** [jgmdev/ddos-deflate#64]
Hello, i used different version of the ddos-deflate and it blocked cloudflare's IP

I see this version is having some cloudflare feature, but i do not know if it would be effective.

Numerous of the hosted sites are using cloudflare. This is Apache + [Cachewall](https://cachewall.com/) with utilize Varnish cache + cloudflare_module

Next thing i want to ask is if it is correct the cloudflare IPs be blocked (that blocked IP shown roughly 3 hundred connections).

I tried to add CF IP ranges in CIDR format into ignore list, but that not worked for the script to match the IPs to the subnet: https://github.com/Amet13/ddos-deflate/issues/4

**Comment by jgmdev** [comment]
I implemented the cloudfare support by using iptables string matching to retrieve the real ip of users given by the cloudflare header value. The implementation details where discussed on #59 

Also CIDR syntax is supported on this fork of ddos-deflate thanks to grepcidr which was contributed by someone else who knew about it.
