### ISSUE TITLE
Can't update scripts

### ISSUE THREAD

**Issue by gagomap** [jgmdev/ddos-deflate#7]
Hello,
I have uninstall an older version of your script (0.7), then install the new one (lastest 0.8), but it show an error:

``` bash
error: Required dependency 'tcpkill' is missing.
```

I'm using EasyEngine on Ubuntu 14.04.3 LTS
Thank you,

//Fixed: Install dsniff package
I think you should auto install Dsniff for ubuntu/debian user.

**Comment by jgmdev** [comment]
Feel free to submit a pull request that detects if distro is debian/ubuntu and run the required apt-install stuff.

**Comment by gagomap** [comment]
I'm not a pro coder :(

**Comment by mohamedaminebelghith** [comment]
when i try to install DDoS Deflate i have this following error and i can't solve it . can someone help me please!
![screenshot from 2015-11-29 23 44 49](https://cloud.githubusercontent.com/assets/16180717/11615723/078b416c-9c69-11e5-8661-1f74f828bb34.png)
error: Required dependency 'tcpkill' is missing.

**Comment by mohamedaminebelghith** [comment]
i try to install DDOs deflate but i have this following error and i can't solve it . can someone help me please ! 

error: Required dependency 'tcpkill' is missing.

**Comment by bxkx** [comment]
Same here.

**Comment by gagomap** [comment]
@mohamedaminebelghith , @bxkx :  Install dsniff package will fixe it

**Comment by bxkx** [comment]
Thank you!

**Comment by jgmdev** [comment]
Implemented on #22 for some distros.
