### ISSUE TITLE
support wildcard domain ？

### ISSUE THREAD

**Issue by crazyfd** [jgmdev/ddos-deflate#71]
/etc/ddos/ignore.host.list  support wildcard domain？
eg:
*.google.com
*.facebook.com

**Comment by jgmdev** [comment]
Currently the code converts the hostname to an ip (or list of ip's) and then adds it to the ip whitelisting. Supporting wildcards would mean doing reverse ip to domain lookup which I'm not even sure how possible it would be or resource intensive since all IP's would need to be reverse checked...
