### ISSUE TITLE
/lib/lsb/init-functions on CentOS 6 (or more ?)

### ISSUE THREAD

**Issue by FrBillyD** [jgmdev/ddos-deflate#8]
Hi, 
I found a bug. When I try to launch the cron, a message appear with :
/etc/init.d/ddos: line 25: /lib/lsb/init-functions: file or directory not found

A post (http://unix.stackexchange.com/questions/9314/no-such-file-or-directory-etc-init-d-functions) advises to install the package "redhat-lsb" with yum, but it want to install 65 additionnal packages...

I continue my research.

Thank you for this "fork", I love this tool ! I use it since 3 years now ! :smile:

**Comment by FrBillyD** [comment]
Installing "redhat-lsb-core" provide only 12 additionnal packages and 16 to update. I try this and I'm waiting another solution if exists. :smiley:

**Comment by FrBillyD** [comment]
Another command is "not found". Is the "log_daemon_msg" in "/etc/init.d/ddos" file.

**Comment by jgmdev** [comment]
I see, it seems I will have to disable all of that to make the startup service more portable
